ci: Fix patch_root not being defined
This fixes the following error:

Traceback (most recent call last):
  File "/sync_patchwork.py", line 458, in <module>
    main()
  File "/sync_patchwork.py", line 432, in main
    ci_data = Context(config_file=os.path.abspath(args.config),
  File "/libs/context.py", line 72, in __init__
    self.patch_root = patch_root
NameError: name 'patch_root' is not defined